// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgRiKQ2JTQwjDSaDC8tGZIIC-TacYJbr0',
    appId: '1:199201173346:web:5a7b52362d3fd311c6c63b',
    messagingSenderId: '199201173346',
    projectId: 'interview-816f5',
    authDomain: 'interview-816f5.firebaseapp.com',
    storageBucket: 'interview-816f5.firebasestorage.app',
    measurementId: 'G-WTDW8LCDRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvM9yJS3mgmUTzvGc4W8zxmwdgrMHfvU',
    appId: '1:199201173346:android:64fb2c7d7e789f9fc6c63b',
    messagingSenderId: '199201173346',
    projectId: 'interview-816f5',
    storageBucket: 'interview-816f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8mvTQGWoTWkwESCcC39sZHFqNwZxE5go',
    appId: '1:199201173346:ios:93342f28ce2a54a1c6c63b',
    messagingSenderId: '199201173346',
    projectId: 'interview-816f5',
    storageBucket: 'interview-816f5.firebasestorage.app',
    iosBundleId: 'com.example.interview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8mvTQGWoTWkwESCcC39sZHFqNwZxE5go',
    appId: '1:199201173346:ios:93342f28ce2a54a1c6c63b',
    messagingSenderId: '199201173346',
    projectId: 'interview-816f5',
    storageBucket: 'interview-816f5.firebasestorage.app',
    iosBundleId: 'com.example.interview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgRiKQ2JTQwjDSaDC8tGZIIC-TacYJbr0',
    appId: '1:199201173346:web:f5f95ea6cfb11214c6c63b',
    messagingSenderId: '199201173346',
    projectId: 'interview-816f5',
    authDomain: 'interview-816f5.firebaseapp.com',
    storageBucket: 'interview-816f5.firebasestorage.app',
    measurementId: 'G-VYQNZE3NNB',
  );
}
